### ISSUE TITLE
First deployment failure

### ISSUE THREAD

**Issue by cisaacstern** [pangeo-forge/AGDC-feedstock#2]
@norlandrhagen, looks like despite the fact that the test run (in staged-recipes) succeeded [here](https://github.com/pangeo-forge/staged-recipes/pull/87#issuecomment-1241126636), the first production run for this feedstock failed: https://github.com/pangeo-forge/AGDC-feedstock/deployments/activity_log?environment=AGCD

I'll take a look at the logs to see why...

**Comment by andersy005** [comment]
This issue has been resolved: https://pangeo-forge.org/dashboard/feedstock/78
